---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurances
  template:
    metadata:
      labels:
        app: insurances
    spec:
      containers:
        - name: insurances
          image: vish042001/insurance-image:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: insurances
spec:
  type: NodePort
  selector:
    app: insurances
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008 
